services:
  jenkins:
    build: .
    container_name: jenkins
    restart: on-failure
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network

volumes:
  jenkins-data:
    driver: local
    name: jenkins-data

networks:
  jenkins-network:
    name: jenkins-network
